#include "forever.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
typedef struct {char *id; char *json;} rec;
struct fw_model {char *version; char *project; rec *records; size_t count;};
static char *readall(const char *p){FILE*f=fopen(p,"rb");long n;char*s;if(!f)return NULL;fseek(f,0,SEEK_END);n=ftell(f);rewind(f);s=malloc((size_t)n+1);if(!s){fclose(f);return NULL;}if(fread(s,1,(size_t)n,f)!=(size_t)n){free(s);fclose(f);return NULL;}s[n]=0;fclose(f);return s;}
static char *jstr(const char *json,const char *key){char pat[96],*p,*s,*o;size_t n=0;snprintf(pat,sizeof pat,"\"%s\"",key);p=strstr(json,pat);if(!p||(p=strchr(p+strlen(pat),':'))==NULL)return NULL;p++;while(isspace((unsigned char)*p))p++;if(*p!='\"')return NULL;s=++p;while(*p&&*p!='\"'){if(*p=='\\'&&p[1])p++;p++;}n=(size_t)(p-s);o=malloc(n+1);if(o){memcpy(o,s,n);o[n]=0;}return o;}
static int add(fw_model*m,char*json){char*id=jstr(json,"id");rec*n;if(!id)return 0;n=realloc(m->records,(m->count+1)*sizeof *n);if(!n){free(id);return 0;}m->records=n;m->records[m->count].id=id;m->records[m->count].json=json;m->count++;return 1;}
fw_model *fw_load(const char *dir,fw_error*e){char path[1024],*man,*p;fw_model*m=calloc(1,sizeof *m);if(!m)return NULL;snprintf(path,sizeof path,"%s/manifest.json",dir);man=readall(path);if(!man){if(e){strcpy(e->code,"io");snprintf(e->message,sizeof e->message,"cannot read %.220s",path);}free(m);return NULL;}m->version=jstr(man,"foreverVersion");m->project=jstr(man,"projectId");p=man;while((p=strstr(p,".json\""))!=NULL){char*q=p;size_t n;while(q>man&&*q!='\"')q--;if(*q!='\"'){p+=6;continue;}n=(size_t)(p+5-q-1);if(n<5||n>=900){p+=6;continue;}memcpy(path,dir,strlen(dir));path[strlen(dir)]='/';memcpy(path+strlen(dir)+1,q+1,n);path[strlen(dir)+1+n]=0;if(strstr(path,"manifest.json")==NULL){char*doc=readall(path);if(doc&&!add(m,doc))free(doc);}p+=6;}free(man);return m;}
void fw_free(fw_model*m){size_t i;if(!m)return;for(i=0;i<m->count;i++){free(m->records[i].id);free(m->records[i].json);}free(m->records);free(m->version);free(m->project);free(m);}
size_t fw_record_count(const fw_model*m){return m?m->count:0;}
const char *fw_get_entity_json(const fw_model*m,const char*id){size_t i;if(!m)return NULL;for(i=0;i<m->count;i++)if(strcmp(m->records[i].id,id)==0)return m->records[i].json;return NULL;}
int fw_validate(const fw_model*m,fw_error*e){size_t i,j;if(!m||!m->version||strncmp(m->version,"0.",2)){if(e){strcpy(e->code,"unsupported-version");strcpy(e->message,"missing or unsupported version");}return 0;}for(i=0;i<m->count;i++){if(!m->records[i].id||!strstr(m->records[i].json,"\"kind\"")){if(e){strcpy(e->code,"missing-required");strcpy(e->message,"record lacks id or kind");}return 0;}for(j=i+1;j<m->count;j++)if(!strcmp(m->records[i].id,m->records[j].id)){if(e){strcpy(e->code,"duplicate-id");strcpy(e->message,m->records[i].id);}return 0;}}return 1;}
static int cmprec(const void*a,const void*b){const rec*x=a,*y=b;return strcmp(x->id,y->id);}
char *fw_serialize(const fw_model*m){rec*copy;char*out,*p;size_t i,n=128;if(!m)return NULL;copy=malloc(m->count*sizeof *copy);if(!copy)return NULL;memcpy(copy,m->records,m->count*sizeof *copy);qsort(copy,m->count,sizeof *copy,cmprec);for(i=0;i<m->count;i++)n+=strlen(copy[i].json)+2;out=malloc(n);if(!out){free(copy);return NULL;}p=out;p+=sprintf(p,"{\"foreverVersion\":\"%s\",\"projectId\":\"%s\",\"records\":[",m->version,m->project);for(i=0;i<m->count;i++){size_t z=strlen(copy[i].json);while(z&&isspace((unsigned char)copy[i].json[z-1]))z--;if(i)*p++=',';memcpy(p,copy[i].json,z);p+=z;}strcpy(p,"]}\n");free(copy);return out;}
