import { readFile } from "node:fs/promises";
import { resolve, dirname, sep } from "node:path";
export type Status="pass"|"fail"|"unknown";
export interface RecordValue { foreverVersion:string; id:string; kind:string; [key:string]:unknown }
export interface Issue {code:string;path:string;message:string;reference?:string}
const refs=new Set(["relatedCapabilities","relatedConstraints","relatedInvariants","relatedImplementations","requiredCapabilities","protectedInvariants","compatibilityObligations","relatedEntities","preservedCapabilities","preservedInvariants","compatibilityImpact","verification","satisfiesCapabilities","constrainedByInvariants","satisfiesConstraints","compatibilityContracts","evidence","sourceImplementation","targetImplementation","currentImplementation"]);
const kinds=new Set(["intent","capability","invariant","constraint","dependency","decision","compatibility","migration","implementation","evidence"]);
function references(r:RecordValue):string[]{const out:string[]=[]; for(const k of refs){const v=r[k]; if(typeof v==="string"&&v.includes("."))out.push(v); else if(Array.isArray(v)) for(const x of v)if(typeof x==="string"&&x.includes("."))out.push(x)} const claims=r.claims; if(Array.isArray(claims))for(const c of claims){if(c&&typeof c==="object"){const x=c as Record<string,unknown>;if(Array.isArray(x.evidence))out.push(...x.evidence.filter((e):e is string=>typeof e==="string"))}}return out}
export class Model {
 readonly entities=new Map<string,RecordValue>();
 constructor(public manifest:Record<string,unknown>,public records:RecordValue[]){for(const r of records)this.entities.set(r.id,r)}
 validate():Issue[]{const errors:Issue[]=[]; const version=this.manifest.foreverVersion;if(typeof version!=="string"||version.split(".")[0]!=="0")errors.push({code:"unsupported-version",path:"manifest.foreverVersion",message:`unsupported version ${String(version)}`});const seen=new Set<string>();this.records.forEach((r,i)=>{for(const k of ["foreverVersion","id","kind"])if(!r[k])errors.push({code:"missing-required",path:`records[${i}].${k}`,message:`missing ${k}`});if(!kinds.has(r.kind))errors.push({code:"invalid-kind",path:`records[${i}].kind`,message:`unknown kind ${r.kind}`});if(seen.has(r.id))errors.push({code:"duplicate-id",path:`records[${i}]`,message:`duplicate ID ${r.id}`});seen.add(r.id)});for(const r of this.records)for(const ref of references(r))if(!this.entities.has(ref))errors.push({code:"broken-reference",path:r.id,reference:ref,message:`unknown reference ${ref}`});return errors.sort((a,b)=>(a.code+a.path+(a.reference??"")).localeCompare(b.code+b.path+(b.reference??"")))}
 getEntity(id:string){return this.entities.get(id)}
 list(kind:string){return this.records.filter(r=>r.kind===kind).sort((a,b)=>a.id.localeCompare(b.id))}
 traceEntity(id:string){if(!this.entities.has(id))throw new Error(`entity not found: ${id}`);const a=new Map([...this.entities.keys()].map(x=>[x,new Set<string>()]));for(const r of this.records)for(const x of references(r))if(a.has(x)){a.get(r.id)!.add(x);a.get(x)!.add(r.id)}const found=new Set<string>(),todo=[id];while(todo.length){const x=todo.pop()!;if(found.has(x))continue;found.add(x);todo.push(...[...a.get(x)!].filter(y=>!found.has(y)))}return [...found].sort().map(x=>this.entities.get(x)!)}
 explainDependency(id:string){const r=this.entities.get(id);if(!r||r.kind!=="dependency")throw new Error(`dependency not found: ${id}`);const out:Record<string,unknown>={};for(const k of ["id","dependencyName","purpose","reasonSelected","replacementClassification","requiredCapabilities","protectedInvariants","relatedConstraints","replacementRequirements","compatibilityObligations","historicalContext","provenance"])if(k in r)out[k]=r[k];return out}
 evaluateReplacement(current:string,candidate:string){const d=this.entities.get(current),c=this.entities.get(candidate);if(!d||d.kind!=="dependency")throw new Error(`dependency not found: ${current}`);if(!c||c.kind!=="implementation")throw new Error(`implementation not found: ${candidate}`);const req:string[]=[];for(const k of ["requiredCapabilities","protectedInvariants","relatedConstraints","replacementRequirements","compatibilityObligations"]){const v=d[k];if(Array.isArray(v))req.push(...v as string[])}return evaluate(candidate,[...new Set(req)],(c.claims??[]) as Claim[])}
 normalized(){return canonical({foreverVersion:this.manifest.foreverVersion,projectId:this.manifest.projectId,records:[...this.records].sort((a,b)=>a.id.localeCompare(b.id))})}
}
type Claim={requirement:string,status:Status,evidence?:string[],reason?:string};
function evaluate(candidate:string,requirements:string[],claims:Claim[]){const by=new Map(claims.map(c=>[c.requirement,c]));const checks=requirements.map(requirement=>by.get(requirement)??{requirement,status:"unknown" as Status,reason:"No candidate evidence supplied"});const states=new Set(checks.map(c=>c.status));return {candidate,result:states.has("fail")?"fail":checks.length>0&&states.size===1&&states.has("pass")?"pass":"partial",checks}}
function sorted(value:unknown):unknown{if(Array.isArray(value))return value.map(sorted);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sorted(v)]));return value}
export function canonical(value:unknown){return JSON.stringify(sorted(value),null,2)+"\n"}
export async function loadModel(input:string):Promise<Model>{let root=input.endsWith("manifest.json")?dirname(input):input;root=resolve(root);const manifest=JSON.parse(await readFile(resolve(root,"manifest.json"),"utf8")) as Record<string,unknown>;const records:RecordValue[]=[];for(const paths of Object.values((manifest.records??{}) as object))if(Array.isArray(paths))for(const rel of paths){const path=resolve(root,String(rel));if(!path.startsWith(root+sep))throw new Error(`record path escapes model root: ${rel}`);records.push(JSON.parse(await readFile(path,"utf8")))}return new Model(manifest,records)}
